18 flaskcliでデータを確認挿入削除できるようにする
kit-isel/SQA pull request #19
Opened 2024-09-24 07:40 UTC by ry05k2ulv

2024-09-24 22:26 UTC, ry05k2ulv commented
click関数内では，print関数ではなくclick.echo関数を使用するべきなので，棄却しておいてください．

2024-09-26 07:04 UTC, miyanagas requested changes

2024-09-26 07:04 UTC, miyanagas commented on backend/app/crud.py
> +    db.session.add(question)
updateするとき、addっていらないんじゃないかな？

2024-09-26 09:20 UTC, miyanagas approved these changes

2024-09-26 09:23 UTC, merged